---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: arm64 

steps:
- name: greeting
  commands:
  - echo hello world

#steps:
#- name: ansible
#  commands:
#  - cd /home/ulf/Documents/git/bitwarden-backup
#  - ansible-playbook -i inventories playbooks/bitwarden-backup.yml
