---
kind: pipeline
type: ssh
name: default

server:
  host: 10.191.77.20
  user: ulf
  password:
    from_secret: rpi4-user

steps:
- name: ansible
  commands:
  - cd /home/ulf/Documents/git/bitwarden-backup
  - ansible-playbook -i inventories playbooks/bitwarden-backup.yml
